title: Gathering Church 2021 Advent Devotional
description: Daily Advent readings written by members of the Gathering Church in Durham, North Carolina.

week_1_theme: The Darkness Did Not Overcome
week_1_passage: The Lord went in front of them in a pillar of cloud by day, to lead them along the way, and in a pillar of fire by night, to give them light, so that they might travel by day and by night. Neither the pillar of cloud by day nor the pillar of fire by night left its place in front of the people.
week_1_passage_verse: — Exodus 13:21-22
week_1_practice: Walk outside this week, stand still and look up into the night. Imagine a pillar of fire guiding you and not letting the darkness overcome your steps. How does it feel to take steps by the Light as it is going before you? Jesus wants you to know he is here and will never leave you.

week_2_theme: Vision in the Night
week_2_passage: But just when he had resolved to do this, an angel of the Lord appeared to him in a dream and said, “Joseph, son of David, do not be afraid to take Mary as your wife, for the child conceived in her is from the Holy Spirit. She will bear a son, and you are to name him Jesus, for he will save his people from their sins.
week_2_passage_verse: — Matthew 1.20-21
week_2_practice: Consider that God wants to bring something vital into the world through you. You will help give others vision in the night. Does the idea of being this important to God frighten you in some way? Take this week’s memory verse about Joseph and substi-tute your name as if God is speaking directly to you. For instance, ‘Sally, daughter of the Brown family, do not be afraid to …’ What does your sentence say?

week_3_theme: Overwhelming Light
week_3_passage: For it was you who formed my inward parts&#59; <br> you knit me together in my mother’s womb. <br> I praise you, for I am fearfully and wonderfully made. <br> Wonderful are your works&#59; <br> that I know very well.
week_3_passage_verse: — Psalm 139.13-14
week_3_practice: If you have a smartphone, record a memo of yourself reading Psalm 139:13-14. Make no judgments about the sound of your voice.<br><br>If you have sight, look in the mirror for as long as you can without making any assessments about the face looking back at you. Now look in the mirror while you listen to your recording of Psalm 139:13-14.<br><br>Your voice and your face are made in the image of God who sees you in the full light of Jesus. End by saying out loud the final verse again, “Wonderful are your works; that I know very well.” Amen.

week_4_theme: Readjusting to the Dark
week_4_passage: Yet more than ever believers were added to the Lord, great numbers of both men and women, so that they even carried out the sick into the streets, and laid them on cots and mats, in order that Peter’s shadow might fall on some of them as he came by.
week_4_passage_verse: — Acts 5.14-15
week_4_practice: Most people in the United States have not carried their sick friends or family members into the streets on cots and mats. But epidemics of loneliness and anxiety affect many of us who go about our daily lives. This week check on someone who may be struggling. Keep your vision adjusted in the darkness so that you can see others. Add them to your heart and home, and introduce them again or for the first time to Jesus.

url: "https://www.gcadvent.com"
gathering_url: http://allgather.org
zoom_link: http://allgather.org/live

markdown: kramdown
future: false
sass:
  sass_dir: src/styles/_sass
