title: Gathering Church 2021 Advent Devotional
description: Daily Advent readings written by members of the Gathering Church in Durham, North Carolina.

week_1_theme: The Darkness Did Not Overcome
week_1_passage: Passage...
week_1_passage_verse: — Colossians 3.1
week_1_practice: Practice...

week_2_theme: Vision in the Night
week_2_passage: Passage...
week_2_passage_verse: — Colossians 3.1
week_2_practice: Practice...

week_3_theme: Overwhelming Light
week_3_passage: Passage...
week_3_passage_verse: — Colossians 3.1
week_3_practice: Practice...

week_4_theme: Readjusting to the Dark
week_4_passage: Passage...
week_4_passage_verse: — Colossians 3.1
week_4_practice: Practice...

url: "https://www.gcadvent.com"
gathering_url: http://allgather.org
zoom_link:

markdown: kramdown
future: false
sass:
  sass_dir: src/styles/_sass
