title: Gathering Church 2020 Advent Calendar
description: Description of the calendar...

week_1_theme: Hold Hope
week_1_passage: Week 1 passage...
week_1_practice: Week 1 practice...

week_2_theme: Bring Peace
week_2_passage: Week 2 passage...
week_2_practice: Week 2 practice...

week_3_theme: Practice Joy
week_3_passage: Week 3 passage...
week_3_practice: Week 3 practice...

week_4_theme: Choose Love
week_4_passage: Week 4 passage...
week_4_practice: Week 4 practice...

week_5_theme: Shine Light
week_5_passage: Week 5 passage...
week_5_practice: Week 5 practice...


url: "https://www.gcadvent.com"
gathering_url: http://allgather.org

markdown: kramdown
future: false
sass:
  sass_dir: src/styles/_sass
