title: Gathering Church 2020 Advent Calendar
description: Description of the calendar...

week_1_theme: Hold Hope
week_1_passage: “Since, then, you have been raised with Christ, set your hearts on things above, where Christ is, seated at the right hand of God.”
week_1_passage_verse: — Colossians 3:1
week_1_practice: Consider your relationships with God, yourself, and others. <br> <br> Make a Christmas list concerning your hopes in each of these relationships. <br> <br> Reflect on your list holding the memory verse near. Cross-off anything that looks like wishful thinking, which is Hope’s imposter. <br> <br> Prayerfully cross off everything from your Christmas list that doesn’t look like hope in Christ. How does that feel to you? <br> <br> Set your list in an important place, e.g. at the foot of the manger where anything worth holding is held.

week_2_theme: Bring Peace
week_2_passage: “I have told you these things, so that in me you may have peace. In this world you will have trouble. But take heart! I have overcome the world.”
week_2_passage_verse: — John 16:33
week_2_practice: Make a short list of words or very brief phrases that bring you a sense of God’s peace. Don’t worry if they seem not to make sense. The Holy Spirit understands them perfectly. <br> <br> In so much as you are able, retreat to a quiet place. Outdoor spaces are especially nice.<br> <br> Repeat the words or phrases slowly, out loud if you are able, until it seems that the cells in your body have rested themselves in their oneness with Christ.<br> <br> With a relaxed inhale and exhale conclude by saying, “Thank you, Jesus.”

week_3_theme: Practice Joy
week_3_passage: “I have much to write to you, but do not want to use paper and ink. Instead, I hope to visit you and talk with you face to face, so that our joy may be complete.”
week_3_passage_verse: — 2 John 1:12
week_3_practice: Think of someone you have not seen in a good while. Select a person, couple or family who you used to see quite regularly. <br> <br> Write a Christmas card to them in your own handwriting. Include a specific memory of a time when you were together face to face. Recall a detail about that time and linger there. In doing so, you practice giving joy to yourself and to the person you are writing. <br> <br> If possible, walk the card to the mailbox imaging that Jesus and you are walking there together.

week_4_theme: Choose Love
week_4_passage: “And over all these virtues put on love, which binds them all together in perfect unity.”
week_4_passage_verse: — Colossians 3:14
week_4_practice: Every time you put on your jacket to go outside this week, say this verse to yourself, or out loud, and experience the Holy Spirit giving you the mantle of Jesus’ love and unity. <br> <br> When you take off your jacket, be mindful of how you set it aside or hang it. Thank God for your material possessions and for warmth. <br> <br> Ask God to keep you in union with the Holy Spirit. <br> <br> Move about your next task with assurance that with God you are sufficient to bring love into the moments that have been given to you.

url: "https://www.gcadvent.com"
gathering_url: http://allgather.org

markdown: kramdown
future: false
sass:
  sass_dir: src/styles/_sass
