name: Daily build

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'Test'
  schedule:
    - cron:  '30 0 * * *'

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: "-X POST -H 'Authorization: token ${{ secrets.DAILY_BUILD_KEY }}' -H 'Accept: application/vnd.github.ant-man-preview+json' https://api.github.com/repos/brandorn/gc-advent/pages/builds"
